### PR TITLE
changed PHP versions to be installed.

### PR DESCRIPTION
**Pull request by srivastava-jyoti**
I have changed php versions to be installed in read.md file.

### CODE REVIEW

**Review by pankaj-ag — APPROVED** [review]
It looks like a simple change. Can you redirect me to the issue for this PR? I am just curious, why 7.3 or higher was not sufficient.

**Comment by srivastava-jyoti** [comment]
There was a compatibility problem of php version 8 with composer. If someone installs version 8 then, while installing composer on git console one need to type,
composer install --ignore-platform-reqs
here, is the reference :-https://github.com/composer/composer/issues/9529

**Comment by P4NK4J** [comment]
@rathorevaibhav , I think we would require updating composer files for higher PHP version compatibilities. Let me know if we can do that in a separate PR and if we are good to merge this pull request.

**Comment by rathorevaibhav** [comment]
@P4NK4J yeah let's target in a separate branch as an overall tech stack update. Merging this.

**Pull request merged**
