### PR TITLE
Now user can send contract for client review and Client can revert back with updates

### PR DESCRIPTION
**Pull request by am-Anmol**
Targets #3157 

### Description

- Created new receiver table migration and model.
- Applied signed URL feature to send client with signed URL.
- Added mail functionality to send, record update notification and finalize notification. 
- Added functionality for client to finalize and update contract fields from signed link.
### Checklist:

- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by GauravGusain98** [comment]
I think this PR needs the PR https://github.com/ColoredCow/portal/pull/3154 to be merged. If yes, then can you change the head branch of this PR to `feature/contract/add-contract` branch

**Comment by am-Anmol** [comment]
> I think this PR needs the PR #3154 to be merged. If yes, then can you change the head branch of this PR to `feature/contract/add-contract` branch

I was thinking to merge this PR #3154 after it got approve, then I'll update the head branch to this PR.

**Comment by am-Anmol** [comment]
Expected Behavior:
- After saving contract `user` can click on `view` button and details of that contract will shown up and from that screen user would be able to `send it for review to client` and a mail will be triggered to client email with signed URL.

- The `client` should be able to `edit` fields through the signed link. If the client makes changes to the form fields, an email should be triggered to the user notifying them of the changes. If the client finalise the contract, a mail should be triggered to the finance team to review the contract.

**Comment by am-Anmol** [comment]
All changes are merged in this PR #3176.
So closing this PR.

**Pull request closed without merging**
