### PR TITLE
Removed start year and replaced end year with year of graduation in a…

### PR DESCRIPTION
**Pull request by shardulgusain**
#1906 

### Description
Removed the start date from filter.
Replaced end date with Year of Graduation.

### Checklist:

- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by P4NK4J** [comment]
@shardulgusain I am getting all the results with graduation year before 2021 using this filter. Please modify the graduation year for a couple of applications and test it out on your local machine

**Review by P4NK4J — CHANGES_REQUESTED** [review]
left some comments, please check

**Review by deepankar-sajwan — APPROVED** [review]

**Comment by P4NK4J** [comment]
@shardulgusain The functionality is not working as expected. Only those applications are appearing, where the applicant graduation year is not found. Please take a look and fix it accordingly.
Try manually changing the year from database for testing or try creating applications from the UI for more data.

**Review by P4NK4J — CHANGES_REQUESTED** [review]
Not working as expected, hence requesting changes

**Pull request closed without merging**
