### PR TITLE
Now user can add contract  (Feature/contract/add contract)

### PR DESCRIPTION
**Pull request by am-Anmol**
Targets #3153 

### Description

- Created migrations for two new table contracts and contracts_meta
- Created model for both above mentioned table.
- Updated UI of index and contract form.
- Updated ProjectContractService index and store function as per new reqiurements.

### Checklist:

- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by GauravGusain98** [comment]
### Testing Feedbacks

1. Can you mention the expected behaviour after your code changes. I am having difficulty understanding what is expected behaviour from this PR

2. I've created a new contract and filled all the details. But when I am editing the contract, I am not seeing any data which I filled
    image

3. While creating a contract, we are providing an input field to enter the client name but when we are editing the contract there we have a dropdown for the client entry and the client name that I entered was not in the list. So how will this new client be available in the dropdown? Are we creating a new client if the client does not exist?

4. On editing the contract and again filling the form. I am getting this error
    image

**Comment by am-Anmol** [comment]
> ### Testing Feedbacks
> 1. Can you mention the expected behaviour after your code changes. I am having difficulty understanding what is expected behaviour from this PR
> 2. I've created a new contract and filled all the details. But when I am editing the contract, I am not seeing any data which I filled
>    image
> 3. While creating a contract, we are providing an input field to enter the client name but when we are editing the contract there we have a dropdown for the client entry and the client name that I entered was not in the list. So how will this new client be available in the dropdown? Are we creating a new client if the client does not exist?
> 4. On editing the contract and again filling the form. I am getting this error
>    image

-----------------------------------------------------------------------
1. Expected behavior:
- User can add a contract by adding `client name` , `contract name`, `date of signing` , `date of effectiveness` and `date of expiry`.
- User can save contract as `draft`.
- User can see all contracts created by him only.

2. Yeah for editing a contract I'm going to cover in next PR, this PR intend to add contract and save as draft.

3. So the existing editing contract page doesn't match with new database structure I was implementing, that's why in update page its not showing inputted values and asking for selecting client from dropdown.

4. I'll be covering editing and update in upcoming issue and PR.

**Comment by GauravGusain98** [comment]
> 2. Yeah for editing a contract I'm going to cover in next PR, this PR intend to add contract and save as draft.

You just need to show the values on the page. Can you do it in this PR only? You can fix the issue that is coming on submitting the for in the next PR

**Comment by am-Anmol** [comment]
Actually I listed edit, update and finalize contract in upcoming issue list, check here #3151. 
Also I have created other PR for user to edit with comments #3169.

**Comment by am-Anmol** [comment]
All changes are merged in this PR #3176.
So closing this PR.

**Pull request closed without merging**
