### PR TITLE
Added a margin between book title and setting button

### PR DESCRIPTION
**Pull request by viveknegi84**
#1775 

### Description
Addition of right margin to book title div to add some gap between the book title and the settings button.

- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by P4NK4J** [comment]
@viveknegi84 can you share a screenshot how it is looking on your end now ?

**Comment by viveknegi84** [comment]
image

**Comment by viveknegi84** [comment]
@P4NK4J Above is the preview on my end.

**Review by P4NK4J — APPROVED** [review]
Looks good.

**Pull request merged**
