### PR TITLE
Added new columns, new tooltips and fixed FTE calculation on user dashboard page

### PR DESCRIPTION
**Pull request by rahulpanwar16**
### Description

- Fixed FTE calculation of current month in monthly FTE report. 
- Added new tooltips to the monthly report data.
- Added new columns ```Project Term``` , ```Expected Hours For Term``` and ```Expected Hours Till Today``` and fetched the corresponding values to the page.

### Checklist:
- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by rahulpanwar16** [comment]
### UNIT TESTING

- Fixed the current month FTE calculation of monthly report data.

Screenshot (183)

- Added new columns ```Project Term``` , ```Expected Hours For Term``` and ```Expected Hours Till Today``` on user dashboard page and fetched it's corresponding data to the page. 

Screenshot (190)

- Added tooltip to the Hours Booked column.
Screenshot (187)

- Added tooltip to the Velocity column.
Screenshot (188)

- Added tooltip to the FTE column.
Screenshot (189)

**Comment by rahulpanwar16** [comment]
**Expected Time**

- Fix the FTE calculation for current month :   1-2 hours.
- Add new columns to the page with it's corresponding data :   1-2 hours.
-  Testing :   0.5 -1 hour.
- Code review and documentation :   0.5-1 hour.


**Actual Spend Time**

1 hour

- Fix the FTE calculation for current month on monthly report.

2 hours

- Added new columns Project Term , Expected Hours For Term and Expected Hours Till Today on user dashboard page and fetched it's corresponding data to the page.
- Added tooltip to the hours booked, velocity and FTE.

1 hour

- For testing, code review and documentation.

### TOTAL TIME SPEND IN A TASK =  4 hours

**Comment by GauravGusain98** [comment]
### Testing feedbacks

1. The project term is not coming correct for projects whose billing date is in between the month. Also calculate days in term according to that 
    image
2. Remove this left margin before project Name. There should be a small margin like on right side of table
    image
3. Make the heading vertically center aligned 
    image
4. In the tooltip replace `timeline` with `term`
    image
5. Show color in this. If hours are greater or equal to expected hours then show it in green color else red
    image

**Comment by Akshiteshnaithani** [comment]
**Expected Time**

- Changes in the Tooltip UI : 6-7 hours
-  Testing : 1 hour
- Code review and documentation : 0.5-1 hour

**Actual Spend Time**
- Fixed the UI 3-4 hour

**Comment by Akshiteshnaithani** [comment]
**Fixed the Tooltip UI**

image

**Comment by GauravGusain98** [comment]
> **Fixed the Tooltip UI**
> 
> image

Can we make it as 
```
FTE: 0.44
Megafit: 0 hrs
GITA: 10 hrs
```

**Comment by Akshiteshnaithani** [comment]
**Updated the feedback**
image

**Comment by GauravGusain98** [comment]
> **Updated the feedback** image

The text format doesnot match the one I shared. 
It should not contain the <name of project>: <hours>

**Comment by Akshiteshnaithani** [comment]
**Implemented**
image

**Comment by GauravGusain98** [comment]
> **Implemented** image

This looks fine. Please push your code.

**Comment by GauravGusain98** [comment]
@Akshiteshnaithani In the chart tooltip can you only show the projects where the hours are greater than 0.

**Comment by GauravGusain98** [comment]
### Testing Feedbacks
1. The data in the chart is showing the complete project hours instead of the hours contributed by the user whose dashboard is open. So please only show the hours that are added by the user and not other team members.

**Comment by GauravGusain98** [comment]
### Testing feedbacks
- Only show projects where hours are not 0 on that month. Currently it is showing all the projects

**Review by GauravGusain98 — APPROVED** [review]
LGTM

**Pull request merged**
