### PR TITLE
Making new row for AMC Projects Automatic Invoices 

### PR DESCRIPTION
**Pull request by rajatsajwan**
Targets #2788

### Description
Making new row Amc Project

### Checklist:

- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by GauravGusain98** [comment]
### Testing feedbacks
1. The financial details of AMC project is not coming from project_billing_details table, its directly coming from client_billing_details.
2. The amount is not getting calculated correctly.

**Comment by rajatsajwan** [comment]
image

**Comment by rajatsajwan** [comment]
sir what is formula for amc amount???

**Comment by rajatsajwan** [comment]
image



sir, is this the correct amount for quarterly ????? 
(1000 * 66 * 3) @GauravGusain98 
image

this table has no data

**Comment by rajatsajwan** [comment]
image

result of change in code

**Comment by GauravGusain98** [comment]
1. The project billing details should be updated from the financial details on project edit page
2. Based on the client billing frequency and billing data you will decide the next billing date of the project. For quarterly, the next billing date will be 3 months after the previous invoice sent_on date. For monthly the next billing date will be the next month date
3. Now to calculate the amount you will use the `service_term` present in project_billing_details

**Comment by rajatsajwan** [comment]
image

i was using  billing date & adding frequency to it to get next billing date.

**Comment by rajatsajwan** [comment]
If we set service Rate 100 /per hour
image
Result:
image

**Comment by rajatsajwan** [comment]
image
these are the changes in amount calculation function

**Comment by GauravGusain98** [comment]
### Testing Feedbacks

The ready-to-send page is not opening. I think you didn't handle the case when a project don't have a project_details entry
image

**Comment by rajatsajwan** [comment]
image
sir i have added check

**Pull request closed without merging**
