### PR TITLE
Generating invoice number for Invoices

### PR DESCRIPTION
**Pull request by Shivam-Samant**
#1342

### CODE REVIEW

**Comment by GauravGusain98** [comment]
@Shivam-Samant The invoice number is not in correct format.
- We don't want hyphen or nay kind of special character in it
- The month and year numbers are missing.

Please check the requirements and make the changes accordingly.

**Comment by GauravGusain98** [comment]
@Shivam-Samant I think there was another requirement as well to calculate gst and igst based on the client state. Are you not covering that in this PR

**Comment by Shivam-Samant** [comment]
> @Shivam-Samant I think there was another requirement as well to calculate gst and igst based on the client state. Are you not covering that in this PR?

This will be done by @Ayush8923 in this PR #1389.

**Review by GauravGusain98 — APPROVED** [review]
LGTM

**Pull request merged**
