### PR TITLE
Feature/1772/fixing new status

### PR DESCRIPTION
**Pull request by ASHISH-KOHLI**
#1772

### Description
new application tag is associated when an application is sent form on hold to resume screening 

### Checklist:
- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Review by P4NK4J — CHANGES_REQUESTED** [review]
@ASHISH-KOHLI This is not as per the requirements. I moved an on-hold application to Resume Screening round, and its status is still showing in-progress, and awaiting confirmation. The application status should be `new` and it should have corresponding tag.

**Comment by ASHISH-KOHLI** [comment]
@P4NK4J okay i will fix it

**Comment by P4NK4J** [comment]
@ASHISH-KOHLI I tested with an application, it seems that moving it to Resume Screening is not correct. Right now, its showing accepted in Resume screening, and then again in Resume screening application is available for evaluation. 
The workflow should be, if an application is in `on-hold`, and from there if its moved to Resume screening, it should appear as a fresh application, like shared in the second screenshot. 
You need to change the status from `on-hold` to `new` in the database and use tags correspondingly
Screenshot 2022-07-19 at 11 38 06 AM

image

**Review by P4NK4J — CHANGES_REQUESTED** [review]
Left some feedback, please check.

**Comment by viveknegi84** [comment]
Sorry for that.😬

**Review by P4NK4J — CHANGES_REQUESTED** [review]
@ASHISH-KOHLI While I am moving an application, its not available for evaluation in resume screening, and in the timeline it is showing that resume screening has already conducted. Please take a look and find how the data is present for new applications, we need to replicate the same in these cases as well (only if an application is moved to resume screening from on hold)
Feel free to reach out if you have any questions.
image

**Review by P4NK4J — APPROVED** [review]
Looks good

**Pull request merged**
