### PR TITLE
Add new book button overlapping fixed

### PR DESCRIPTION
**Pull request by Ayush8923**
Targets #2915 
### Description
In mobile, on the book module theadd new button is overlapping so, i fixed it.
### Checklist:
- [X] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by Ayush8923** [comment]
Please remove the `package.lock.json` file changes from this PR. `package.lock.json` file changes are not needed.

**Review by Ayush8923 — COMMENTED** [review]
@akshatsemwal146   Please remove the `package.lock.json` file changes from this PR. `package.lock.json` file changes are not needed.

**Review by Hemrajbharti123 — CHANGES_REQUESTED** [review]
Can you revert the package-lock.json file , it should not be shown in the PR

**Comment by akshatsemwal146** [comment]
> Can you revert the package-lock.json file , it should not be shown in the PR

Sorry can't get you, could you tell me what to do exactly?

**Comment by Hemrajbharti123** [comment]
In your file changes this file is also shown so u have to delete package-lock.json file such that this is not shown in the file changes

image

**Comment by akshatsemwal146** [comment]
i am creating a new pull request#3022 because i encounter some problem in previous one.

**Pull request closed without merging**
