### PR TITLE
Hr module seeder

### PR DESCRIPTION
**Pull request by belwalshubham**
Targets #1752 

### Description
fixing all the seeders in the HR module and create seeder for all the remaining table of Hr Module.

### Checklist:
- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by srivastava-jyoti** [comment]
There are some failing checks on your pr. Please check and then assign for review

**Comment by belwalshubham** [comment]
> There are some failing checks on your pr. Please check and then assign for review

Done.

**Comment by gautam071** [comment]
@belwalshubham Looks like the PR checks are still failing. Can you take a look

**Comment by belwalshubham** [comment]
closing this PR in favor of https://github.com/ColoredCow/portal/pull/2236

**Pull request closed without merging**
