### PR TITLE
Create feature to add payment schedule of project

### PR DESCRIPTION
**Pull request by yuvraj752**
Targets #2889 

### Description
1. Made migrations to add billing_frequency and billing_level columns in project_billings_details.
2. Rename project type to billing frequency in both UI and database tables projects and project_billings_details.
3. Move billing frequency and billing level UI from project details tab to project financial details tab.
4. Store the values submitted by the form to the database tables projects, project_meta and project_billings_details.
5. Made the necessary changes in how the UI will be rendered after the database migrations and test thoroughly and make sure we are not breaking anything.
6. Made the migrations to store the existing data to our updated database tables.

### Checklist:

- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Review by pankaj-ag — APPROVED** [review]

**Comment by yuvraj752** [comment]
https://user-images.githubusercontent.com/49526581/229363839-f372a225-989d-4ff6-810a-ee2e06400883.mp4

**Comment by pankaj-ag** [comment]
@GauravGusain98 we recently made some changes in the project billing table. Can you check this PR once and see in case it's effecting any usecase in the invoicing module ?

**Comment by GauravGusain98** [comment]
@pankaj-ag This functionality is incomplete as we discussed earlier. Do we need this PR?

**Comment by GauravGusain98** [comment]
This functionality is incomplete. And the person working on this PR is not active now. Closing this PR

**Pull request closed without merging**
