### PR TITLE
Added a new user in User_table

### PR DESCRIPTION
**Pull request by vipulgoyal006**
Targets #1018

### Description
Updated users table seeder to add a new user

### Checklist:

- [x] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by GauravGusain98** [comment]
@vipulgoyal006 I see that some checks are getting failed. Can you fix the formatting of your code? You can see the details section of the failed checks to see on which line error is occurring. 

Note: Add `ready for review` label only when all the checks are pased.

**Comment by vipulgoyal006** [comment]
@GauravGusain98  sorry about the failed checks earlier. I have fixed the issues now.

**Comment by GauravGusain98** [comment]
@am-Anmol @vipulgoyal006 I have merged a PR related to seeders today. There we have user seeder that create new entry for a user whenever we run the seeder command. To run that you can use the command php artisan module:seed User

I think we can close this PR as the functionality has already been created

**Comment by vipulgoyal006** [comment]
As per the above conversation, I will close this PR now.

**Pull request closed without merging**
