### PR TITLE
responsive-ledger-accounts-page

### PR DESCRIPTION
**Pull request by MayankMukul**
Targets #{2944}

### Checklist:

- [ ] I have performed a self-review of my own code.

### CODE REVIEW

**Comment by Hemrajbharti123** [comment]
### Local Testing Feedback

Compared to other pages in the portal width of the table is too large than others 

image

**Comment by GauravGusain98** [comment]
> ### Local Testing Feedback
> Compared to other pages in the portal width of the table is too large than others
> 
> image

This is correct. For now it will not create any issue. The task was to make it responsive, so you need to check if the table is looking fine in small screen or not.

**Comment by GauravGusain98** [comment]
@MayankMukul In small screen i.e 375px. The page UI is not looking fine. 

You need to decrease the font size as well so that they come in one line. I think you have just made changes to table. Also, if you are a user then do you think this UI is looking good? I guess not, So when submitting your PR don't just think of completing the task also see what you have made and how a user will feel by seeing the changes you have done
image

**Comment by Ayush8923** [comment]
Closing this PR because suggested changes are not implemented and the Assignee is not working in this.

**Pull request closed without merging**
