### PR TITLE
Show code coverage as a comment on github PR

### PR DESCRIPTION
**Pull request by pankaj-ag**

### CODE REVIEW

**Comment by pankaj-ag** [comment]
@Sachinbisht27 the action you used having an issue since the comment is a bit long. Please check.

**Comment by Sachinbisht27** [comment]
> @Sachinbisht27 the action you used having an issue since the comment is a bit long. Please check.

Yes @pankaj-ag Checking

**Comment by Sachinbisht27** [comment]
Updated @pankaj-ag. The coverage details are on the PR now.

**Review by Sachinbisht27 — APPROVED** [review]
LGTM. Approved.

**Pull request merged**
